# Added by Ronja Gueldenring
# For spawning agents dynamically in pedsim and forwarding them to flatland
string id
geometry_msgs/Point pos
int16 type
int16 number_of_peds
geometry_msgs/Point[] waypoints
---
bool success
